Do not rely upon LSB wrappers - use start-stop-daemon directly
This isn't required for Gunicorn - just for Klever Controller and schedulers that aren't perfect daemons.

diff --git a/deploys/init.d/klever-bridge b/deploys/init.d/klever-bridge
--- a/deploys/init.d/klever-bridge
+++ b/deploys/init.d/klever-bridge
@@ -38,28 +38,39 @@ DIR=/var/www/"$NAME"
 case "$1" in
     start)
         log_daemon_msg "Starting $DESC"
-        start_daemon -p ${PIDFILE} ${DAEMON} --daemon --pid ${PIDFILE} --chdir ${DIR} --timeout 900 \
-            --workers $(( 2 * `cat /proc/cpuinfo | grep 'core id' | wc -l` + 1 )) --bind unix:${DIR}/gunicorn.sock \
-            bridge.wsgi:application
-        log_end_msg $?
+        if [ -s ${PIDFILE} ] && kill -0 $(cat ${PIDFILE}) >/dev/null 2>&1; then
+            log_progress_msg "apparently already running"
+            log_end_msg 0
+            exit 0
+        fi
+        if start-stop-daemon --start --quiet --background --pidfile ${PIDFILE} --make-pidfile --exec ${DAEMON} \
+            -- --chdir ${DIR} --timeout 900 --workers $(( 2 * `cat /proc/cpuinfo | grep 'core id' | wc -l` + 1 )) \
+            --bind unix:${DIR}/gunicorn.sock bridge.wsgi:application
+        then
+            rc=0
+            sleep 1
+            if ! kill -0 $(cat ${PIDFILE}) >/dev/null 2>&1; then
+                log_failure_msg "$DESC failed to start"
+                rc=1
+            fi
+        else
+            rc=1
+        fi
+        if [ ${rc} -eq 0 ]; then
+            log_end_msg 0
+        else
+            log_end_msg 1
+            rm -f ${PIDFILE}
+        fi
         ;;
     stop)
         log_daemon_msg "Stopping $DESC"
-        killproc -p ${PIDFILE} ${DAEMON}
-        RETVAL=$?
-        [ ${RETVAL} -eq 0 ] && [ -e ${PIDFILE} ] && rm -f ${PIDFILE}
-        log_end_msg ${RETVAL}
-        ;;
-    restart)
-        log_daemon_msg "Restarting $DESC"
-        $0 stop
-        $0 start
-        ;;
-    status)
-        status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME} && exit 0 || exit $?
+        start-stop-daemon --stop --quiet --oknodo --pidfile ${PIDFILE}
+        log_end_msg $?
+        rm -f ${PIDFILE}
         ;;
     *)
-        log_action_msg "Usage: $SCRIPTNAME {start|stop|status|restart}"
+        log_action_msg "Usage: $SCRIPTNAME {start|stop}"
         exit 2
         ;;
 esac
